name: isibi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  appinio_video_player: ^1.2.2
  auto_size_text: 3.0.0
  camera: ^0.10.5+4
  carousel_slider: ^4.2.1
  chewie: ^1.7.1
  clickable_widget: ^0.0.5
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  easy_search_bar: ^2.5.0
  flutter:
    sdk: flutter
  flutter_tflite: ^1.0.1
  get: 4.6.5
  google_fonts: ^5.1.0
  http: ^1.1.0
  image: ^3.2.0
  lint: ^2.1.2
  permission_handler: ^11.0.0
  tflite_flutter: ^0.10.2
  video_player: ^2.7.2

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/isibi.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/ic_foreground.png"

flutter:
  assets:
    - assets/models/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
  uses-material-design: true
